<?php
use Drupal\mall\Entity\Category;
use Drupal\mall\Entity\Item;
use Drupal\mall\Mall;
use Drupal\mall\x;
use Symfony\Component\Yaml\Yaml;

function mall_theme()
{
  $routes = Yaml::parse(file_get_contents(drupal_get_path('module', 'mall').'/mall.routing.yml'));   
  $themes = [];
  foreach($routes as $name => $info) {
    $themes[$name] = [
      'variables' => [ 'data' => null],
      'template' => $name
    ];
		
  }
  
  return $themes;
}

function mall_preprocess(&$variables, $hook)
{
  if ( ! x::isMallPage() ) {
    return;
  }

  $variables['x']['months'] = x::$months;
  $variables['input'] = x::getInput();
  if( $variables['input']['category'] ){
	$variables['category_root'] = x::getCategoryRoot( $variables['input']['category'] );	
  }
  else if( $entity_category_id ){
	
  }

  /*this is a bad place fore these
	  if( empty( $variables['input']['category_root'] ) && $variables['input']['category']  ){
		$variables['input']['category_root'] = $variables['input']['category'];
	  }  
  eo this is a bad place fore these*/
  
	$variables['#attached']['library'][] = 'mall/default';
	//$request = \Drupal::request();

	// page classes
	if ( $hook == 'mall' ) {
	 //$variables['categories'] = Mall::categoryList( $variables );

	}
	else{
		//echo $hook;
	}
}


function mall_entity_load( array $entities, $type ){	
	if( $type == 'mall_item' ){		
		$entity_category_id = array_values($entities)[0]->category_id->target_id;
	}
}